### ISSUE TITLE
Sound doesn't work under Yosemite

### ISSUE THREAD

**Issue by LisannaDettwyler** [artyfarty/bb-osx#1]
Builds fine, but no instructions are provided from "make" for enabling sound. The demo runs fine but without sound. Have not tested on earlier versions of OSX.

**Comment by edagarli** [comment]
install finished ，then how to start?

**Comment by artyfarty** [comment]
`bb`

You can skip install and run binary with `./bb` from project root.

**Comment by edagarli** [comment]
that's fantastic
